name: Beta Release builds

on:
  pull_request:
    branches: ["me"]
  push:
    branches: ["me"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  changelog:
    name: Beta Release Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Create or update ref
        id: create-or-update-ref
        uses: ovsds/create-or-update-ref-action@v1
        with:
          ref: tags/beta
          sha: ${{ github.sha }}

      - name: Create beta release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release view beta || gh release create beta --prerelease

  release:
    runs-on: ubuntu-latest
    needs:
      - changelog
    strategy:
      fail-fast: false
      matrix:
        goos: [windows, linux]
        goarch: [amd64]
        goarm: [""]
        ldflags: [""]
        include:
          - goos: android
            goarch: arm64
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOARM: ${{ matrix.goarm }}
      CGO_ENABLED: 0
      APP_NAME: openlist
      ASSET_NAME: "${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goarm }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup NDK
        if: matrix.goos == 'android'
        run: |
          wget -qO android-ndk.zip https://dl.google.com/android/repository/android-ndk-r29-linux.zip
          unzip android-ndk.zip
          rm android-ndk.zip
          declare -A arches=(
            ["amd64"]="x86_64-linux-android24-clang"
            ["arm64"]="aarch64-linux-android24-clang"
          )
          echo CC="$(realpath android-ndk-*/toolchains/llvm/prebuilt/linux-x86_64/bin)/${arches[${{ matrix.goarch }}]}" >> $GITHUB_ENV
          echo CGO_ENABLED=1 >> $GITHUB_ENV

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version: stable

      - name: Show go env
        run: |
          go env

      - name: Setup web
        run: bash build.sh dev web
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FRONTEND_REPO: ${{ vars.FRONTEND_REPO }}

      - name: Get project dependencies
        run: go mod download

      - name: Build
        run: |
          mkdir -p build
          appName="${{ env.APP_NAME }}"
          builtAt="$(date +'%F %T %z')"
          gitAuthor="The OpenList Projects Contributors <noreply@openlist.team>"
          gitCommit=$(git log --pretty=format:"%h" -1)
          git tag -d beta || true
          # Always true if there's no tag
          version=$(git describe --abbrev=0 --tags 2>/dev/null || echo "beta")
          webVersion="rolling"
          ldflags="-X 'github.com/OpenListTeam/OpenList/v4/internal/conf.BuiltAt=$builtAt' \
          -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.GitAuthor=$gitAuthor' \
          -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.GitCommit=$gitCommit' \
          -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.Version=$version' \
          -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.WebVersion=$webVersion' \
          ${{ matrix.ldflags || '-w -s' }} \
          -buildid="
          if [[ "${{ matrix.goos }}" == 'windows' ]]; then
            appName="$appName.exe"
          fi
          go build -o build/$appName -trimpath -buildvcs=false -ldflags="$ldflags" -tags=jsoniter -v .

      - name: Compress
        if: github.event_name != 'pull_request'
        run: |
          mkdir -p build_compress
          cd build
          if [[ "${{ matrix.goos }}" == 'windows' ]]; then
            zip -j ../build_compress/${{ env.APP_NAME }}-${ASSET_NAME}.zip *
          else
            tar -czf ../build_compress/${{ env.APP_NAME }}-${ASSET_NAME}.tar.gz *
          fi

      - name: Upload assets to beta release
        if: github.event_name != 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in build_compress/*; do
            gh release upload beta "$file" --clobber
          done

      - name: Upload files to Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.APP_NAME }}-${{ env.ASSET_NAME }}
          path: build/*
